cursor            #e0c46d
cursor_text_color #3c2f00

foreground            #e9e2d4
background            #110e07
selection_foreground  #383016
selection_background  #d4c6a1
url_color             #d4c6a1

#: black 000000 767676
color0  #16130b
color8  #38342b
#: red cc0403 f2201f
color1  #d6b45f
color9  #f5edd9
#: green 19cb00 23fd00
color2  #d4c6a1
color10 #f0e1bb
#: yellow cecb00 fffd00
color3  #accfaf
color11 #c7ecca
#: blue 0d73cc 1a8fff
color4  #564500
color12 #e0c46d
#: magenta cb1ed1 fd28ff
color5  #4f462a
color13 #d4c6a1
#: cyan 0dcdcd 14ffff
color6  #2e4e35
color14 #accfaf
#: white dddddd ffffff
color7  #cec6b4
color15 #e9e2d4

mark1_foreground #231b00
mark1_background #fee086
mark2_foreground #221b04
mark2_background #f0e1bb
mark3_foreground #02210d
mark3_background #c7ecca

active_tab_foreground #3c2f00
active_tab_background #e0c46d
inactive_tab_foreground #fee086
inactive_tab_background #564500

active_border_color #e0c46d
inactive_border_color #3c2f00
# bell_border_color #ff5a00
