font_family                     JetBrainsMono Nerd Font
font_size                       13

disable_ligatures               no
enable_audio_bell               no

shell_integration               disabled

cursor_shape                    block
url_style                       curly

background_opacity              1
remember_window_size            no
window_padding_width            21.75
cursor_blink_interval           -1
cursor_trail                    10
cursor_trail_decay              0.1 0.9
scrollbar_handle_opacity        0
scrollbar_track_opacity         0
scrollbar_track_hover_opacity   0

confirm_os_window_close         0

sync_to_monitor                 no

repaint_delay                   8
input_delay                     3


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
