no-osd-bar

profile=gpu-hq
hwdec=auto-safe

gpu-context=wayland
deband=yes
deband-iterations=2
deband-threshold=45
deband-range=16
deband-grain=15


dither-depth=auto
dither=fruit


sub-auto=fuzzy
sub-font="sans-serif"
sub-font-size=40
sub-color=#FFFFFFFF
sub-border-color=#FF000000
sub-border-size=2.0