[config]


[config.wallpaper]
command = "awww img --transition-type center {{ image }}"
set = false

[templates.hyprland]
input_path = '/home/laxhya/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.waybar]
input_path = '/home/laxhya/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '/home/laxhya/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.rofi]
input_path = '/home/laxhya/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.fuzzel]
input_path = '/home/laxhya/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.btop]
input_path = '/home/laxhya/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.starship]
input_path = '/home/laxhya/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.vesktop]
input_path = '/home/laxhya/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.spotify]
input_path = '/home/laxhya/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'

[templates.gtk3]
input_path = '/home/laxhya/.config/matugen/templates/gtk3.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '/home/laxhya/.config/matugen/templates/gtk4.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.yazi]
input_path = '/home/laxhya/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.pywalfox]
input_path = '/home/laxhya/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.dunst]
input_path = '/home/laxhya/.config/matugen/templates/dunstrc-colors.txt'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[templates.obs]
input_path = '/home/laxhya/.config/matugen/templates/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'
